site_name: Boat Stuff
site_url: https://jeryrb.github.io/boatstuff
site_author: jey
site_description: Boat related data including available products

repo_name: boatstuff
repo_url: https://github.com/jeyrb/boatstuff

docs_dir: docs/
copyright: '© jey burrows 2025'

theme:
  name: material

plugins:
  - marimo: {}
  - search
  - gen-files:
      scripts:
        - src/prepare/numbers_to_sqlite.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:


validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn