---
name: Github Pages Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files_yaml: |
            requirements:
              - "pyproject.toml"
              - "uv.lock"
              - "mkdocs.yml"
            docs:
              - "docs/**"
              - "mkdocs.yml"
            data:
              - "data/**"

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install dependencies
        id: install-deps
        run: |
          uv venv
          uv pip install mkdocs-material mkdocs-marimo mkdocs-gen-files pymdown-extensions
      - name: Build and deploy docs
        id: build-docs
        run: |
          uv run mkdocs gh-deploy --force
